# Generated by Django 5.1.3 on 2024-11-25 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userregistration',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('lastname', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('username', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('email', models.CharField(blank=True, default=0, max_length=200, null=True, unique=True)),
                ('password', models.CharField(blank=True, default=0, max_length=200, null=True)),
                ('mobile', models.CharField(blank=True, default=0, max_length=200, null=True, unique=True)),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('deletedDate', models.DateTimeField(auto_now=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
                ('loginDateTime', models.DateTimeField(auto_now=True)),
                ('logoutDateTime', models.DateTimeField(auto_now=True)),
                ('access_id', models.IntegerField(blank=True, default=0, null=True)),
                ('is_authenticated', models.IntegerField(blank=True, default=0, null=True)),
                ('access_token', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
