# Generated by Django 5.1.3 on 2024-11-27 07:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='access_id',
        ),
    ]
